version: "3"

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        env_file:
            - .env
        ports:
            - "3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - net

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        env_file:
            - .env
        ports:
            - "9000"
        depends_on:
            mariadb:
                condition: service_started
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - net

    nginx:
        build: ./requirements/nginx
        container_name: nginx
        env_file:
            - .env
        ports:
            - "443:443"
        depends_on:
            wordpress:
                condition: service_started
        networks:
            - net
        volumes:
            - wordpress_data:/var/www/html

networks:
    net:
        driver: bridge

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/mariadb
        
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress
